### ISSUE TITLE
[minor] SBT complains about missing bintray credentials on startup

### ISSUE THREAD

**Issue by maciej** [softwaremill/supler#52]
It's a minor thing, but SBT complains about missing bintray credentials when running tasks, that do not require those credentials, like `test`
```
[warn] Credentials file /Users/maciejb/.bintray/.artifactory does not exist
```

**Comment by pranjut** [comment]
Any update on this warning?

**Comment by UtkarshaS** [comment]
Getting a similar error. Did you get a solution?

**Comment by adamw** [comment]
Should be gone now :)
