### ISSUE TITLE
getting some errors in supler

### ISSUE THREAD

**Issue by binkabir** [softwaremill/supler#61]
TypeError: formJson.fields.forEach is not a function
this is what I get in my browser console  when trying to load a page with supler. 
any idea as to this error?

**Comment by adamw** [comment]
Which browser / OS?

**Comment by binkabir** [comment]
but chrome and firefox log the same error, Im using ubuntu 15.04

**Comment by adamw** [comment]
Ok, so it's not IE6 ;-) How are you receiving form data on the frontend? Would it be possible to see the JSON or at least check if it has a `main_form.fields` property?

**Comment by binkabir** [comment]
this is the json object from spray 
             {"is_supler_form":true,"main_form":{"fields":{"name":{"label":"name ","type":"string","validate":{"required":true},"path":"name","value":"kabir","empty_value":"","enabled":true},"age":{"label":"age","type":"integer","validate":{"required":true},"path":"age","value":34,"empty_value":0,"enabled":true}}},"errors":[]}

**Comment by adamw** [comment]
Hmm can you check which version of the supler jar do you have? It seems outdated.

**Comment by binkabir** [comment]
I was using supler 0.2.3, now I upgraded to 0.3.0 everything went fine :) . 
I think you should add the latest sbt library on the front page of the readme file, to ensure that every new comer will clone the latest built. Many thanks for this library.

**Comment by adamw** [comment]
Glad that it works! There's a "maven central" badge at the very top, but the docs where outdated, so I'm fixing that - thanks!
